# Report Automation — web app + capture pipeline in one image.
#
# Targets Hugging Face Spaces (Docker SDK) but is deliberately host-agnostic:
# nothing HF-specific is baked in beyond the default port, so the same image
# runs unchanged on a VM via docker-compose.
#
# Base: the official Playwright Python image — published for amd64 AND arm64,
# with Chromium and every OS library it needs already installed. That avoids the
# fragile `playwright install-deps` step entirely.
# The tag MUST match the playwright version in requirements.txt.
FROM mcr.microsoft.com/playwright/python:v1.61.0-noble

# Hugging Face Spaces serves the container on port 7860 and runs it as UID 1000.
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=7860 \
    DATA_DIR=/app/data \
    SESSIONS_DIR=/app/sessions \
    HOME=/app

WORKDIR /app

# Dependencies first so code edits don't invalidate the layer.
COPY requirements.txt requirements-web.txt ./
RUN pip install --no-cache-dir --break-system-packages \
        -r requirements.txt -r requirements-web.txt

# The frozen X pipeline, the influencer pipeline, and the web layer.
COPY run.py save_login.py install.py ./
COPY src/ ./src/
COPY influencer/ ./influencer/
COPY webapp/ ./webapp/

# Runtime state. On Hugging Face the filesystem is EPHEMERAL — these are wiped
# on every restart, which is fine by design: the X session is regenerated by
# signing in again (webapp/x_login.py) and finished reports are downloaded
# straight away. A VM can mount volumes over these paths instead.
#
# The base image already has a UID 1000 user (pwuser); create one only if some
# future base image does not. Running as 1000 is what Hugging Face expects.
RUN mkdir -p /app/data /app/sessions \
 && if ! id -u 1000 >/dev/null 2>&1; then useradd -m -u 1000 appuser; fi \
 && chown -R 1000:0 /app \
 && chmod -R g+rwX /app

USER 1000

EXPOSE 7860

HEALTHCHECK --interval=30s --timeout=5s --start-period=25s --retries=3 \
  CMD python -c "import os,urllib.request;urllib.request.urlopen('http://127.0.0.1:'+os.environ.get('PORT','7860')+'/health').read()"

# One worker process: job state lives in this process's thread pool, so scaling
# means raising MAX_CONCURRENT_JOBS, not adding uvicorn workers.
CMD ["sh", "-c", "exec uvicorn webapp.main:app --host 0.0.0.0 --port ${PORT:-7860} --workers 1 --proxy-headers --forwarded-allow-ips='*'"]
